name: goreleaser

on:
  push:
    branches:
      - synapse/master
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow


      - name: Bump and push
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.143.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
